config/routes.rb
Rails.application.routes.draw do
  # get 'shopping_lists/show'
  get 'shopping_list', to: 'shopping_lists#show'
    get 'public_recipes', to: 'recipes#public_recipes'

  resources :recipes do
    member do
      patch :toggle
    end
    resources :recipes_foods, only: [:new, :create]
  end
  resources :foods 
  # devise_for :users
  devise_for :users, sign_out_via: [:get, :delete]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  def total_cost
    total = 0
    recipe_foods.each do |recipe_food|
      total += recipe_food.food.price * recipe_food.quantity
    end
    total
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show public_recipes]
  # before_action :current_user!, only: %i[edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all.order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @user_foods = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new

    return if current_user

    flash[:notice] = 'You must be logged in to add a new recipe.'
    redirect_to root_path
  end

  # GET /recipes/1/edit
  def edit
    return if current_user

    flash[:notice] = 'You must be logged in to add a edit recipe.'
    redirect_to root_path
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.foods.destroy_all
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # recipes_controller.rb
  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: "Recipe is now #{@recipe.public ? 'public' : 'private'}"
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(recipe_foods: [:food]).order(created_at: :desc)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end

  # def current_user!
  #   @recipe = current_user.recipes.find_by(id: params[:id])

  #   return unless @recipe.nil?

  #   redirect_to recipes_path, notice: 'Not authorized to edit this recipe'
  # end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control mt-2" %>
  </div>

  <div class="form-field my-3">
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.number_field :preparation_time, class:"form-control mt-2" %>
  </div>

  <div class="form-field">
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.number_field :cooking_time, class:"form-control mt-2" %>
  </div>

  <div class="form-field my-3">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class:"form-control mt-2" %>
  </div>

  <div class="form-field d-flex gap-3">
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public, class:"mt-2" %>
  </div>

  <div class="form-field my-3">
    <% form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, value:current_user.id, type: :hidden %>
  </div>

  <div class="form-field">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/edit.html.erb
<% content_for :title, "#{@recipe.name}" %>

<div class="row justify-content-center my-5">
  <div class="col-6 card p-5">
    <h1 class="text-center">Editing recipe</h1>

    <%= render "form", recipe: @recipe %>

    <br>

    <div>
      <%= link_to "Show this recipe", @recipe %> |
      <%= link_to "Back to recipes", recipes_path %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<% content_for :title, "Recipes" %>
<h1>Recipes</h1>

<% if user_signed_in? %>
  <%= link_to raw('<i class="fas fa-plus"></i> New recipe'), new_recipe_path, class: "btn btn-outline-secondary" %>
<% end %>

<div class="my-5">
  <% @recipes.each do |recipe| %>
    <%= link_to recipe_path(recipe), class:"text-dark link-offset-2 link-underline link-underline-opacity-0" do %>
      <div class="row g-0 border p-4 my-3">
        <div class="col-md-6">
          <h3><%= recipe.name %></h3>
          <% if can?(:edit, recipe) %>
            <%= button_to "Delete this recipe", recipe, method: :delete, class: "btn btn-danger my-3" %>
          <% end %>
        </div>
        <div class="col-md-6">
          <p><%= recipe.description %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<% content_for :title, "New recipe" %>

<div class="row justify-content-center my-5">
  <div class="col-6 card p-5">
    <h1 class="text-center">New recipe</h1>

    <%= render "form", recipe: @recipe %>

    <br>

    <div>
      <%= link_to "Back to recipes", recipes_path %>
    </div>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div>
<div class="recipe-title">
<h1 >Public Recipes</h1>
</div>
<ul>
  <% @public_recipes.each do |recipe| %>
    <li class="recipe-card my-5">
    <div class="recipe-main">
    <h2><%= link_to recipe.name, recipe %></h2>
    <h4>By <%= recipe.user.name %></h4>
    </div>
    <div class="recipe-sub">
    <p>Total foods Items <%= recipe.foods.count %></p>
     <p>Total Cost: <%= number_to_currency(recipe.total_cost) %></p>
    </div>
    </li>
  <% end %>
</ul>
</div>

app/views/recipes/shopping_list.erb
<!-- shopping_list.html.erb -->


<div class="d-flex text-center">
  <div class="col-md-6">
    <h3>Amount of food items to buy <%= @total_count  %></h3>
  </div>
  <div class="col-md-6">
    <h3>Total value of food needed $<%= @total_price %></h3>
  </div>
</div>

<div class="row">
  <h1 class="text-center">Shopping List</h1>
  
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
      <% @missing_foods.each_with_index do |food, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td>$<%= food.price %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if @missing_foods.any? %>
  <ul>
    <% @missing_foods.each do |food| %>
      <li><%= food.name %> (Quantity: <%= food.quantity %>)</li>
    <% end %>
  </ul>
  <p>Total Price of Missing Food: $<%= @total_price %></p>
<% else %>
  <p>No missing food items.</p>
<% end %>

app/views/recipes/show.html.erb
<% content_for :title, "#{@recipe.name}" %>

<div class="row gap-3 my-5">
  <div class="d-flex justify-content-between align-items-center">
    <div class="recipe-main">
      <h4>Preparation time: <%= @recipe.preparation_time %></h4>
    </div>
    <div class="recipe-sub">
      <% if can?(:edit, @recipe) %>
          <div class="form-group d-flex gap-3 align-items-center form-switch">
            <%= button_to "#{@recipe.public ? 'Private' : 'Public'}", 
                toggle_recipe_path(@recipe),
                method: :patch,
                class: "btn btn-link link-offset-2 link-underline link-underline-opacity-0" 
              %>
              <%= button_tag type: 'submit', class: "btn" do %>
                <input type="checkbox" name="recipe[public]" class="form-check-input" <%= 'checked' if @recipe.public? %>>
              <% end %>
          </div>
        <% end %>
    </div>
  </div>
  <div class="recipe-main">
    <h4>Cooking time: <%= @recipe.cooking_time %></h4>
  </div>
  <div class="recipe-main">
    <p><%= @recipe.description %></p>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center">
  <% if can?(:edit, @recipe) %>
    <%= link_to "Generate Shopping List", shopping_list_path, class: 'btn btn-outline-secondary' %>
  <% end %>
  <% if can?(:edit, @recipe) %>
    <a href="<%= new_recipe_recipes_food_path(@recipe) %>" class="btn btn-outline-secondary my-3">Add ingredient</a>
  <% end %>
</div>

<hr class="my-3" />

<div class="row my-5 gap-5">
  <div class="col-md-12">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
        </tr>
      </thead>
      <tbody>
      <% @user_foods.each_with_index do |food, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td>$<%= food.price %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>