config/routes.rb
Rails.application.routes.draw do
  # get 'shopping_lists/show'
  get 'shopping_list', to: 'shopping_lists#show'
    get 'public_recipes', to: 'recipes#public_recipes'

  resources :recipes do
    member do
      patch :toggle
    end
    resources :recipes_foods, only: [:new, :create]
  end
  resources :foods 
  # devise_for :users
  devise_for :users, sign_out_via: [:get, :delete]

  # Defines the root path route ("/")
  root "home#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /foods or /foods.json
  def index
    @foods = Food.all.order(id: :desc)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new

    return if current_user

    flash[:notice] = 'You must be logged in to add a new food.'
    redirect_to root_path
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.recipes.destroy_all
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end

  # def current_user!
  #   @food = current_user.foods.find_by(id: params[:id])

  #   return unless @food.nil?

  #   redirect_to foods_path, notice: 'Not authorized to edit this food'
  # end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
    <div class="col-md-12 <%= dom_id food %>">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0"><%= food.name %></h3>
          <div class="mb-1 text-body-secondary"><%= food.created_at.strftime('%d %b %y') %></div>
          <p class="card-text mb-ato">Price: $<%= food.price %></p>
          <i class="d-inline-block mb-2 text-primary-emphasis">Created by: <%= food.user.name %></i>
          <%= link_to "Show this food", food, class:"icon-link gap-1 icon-link-hover stretched-link" %>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="https://scalebranding.com/wp-content/uploads/2020/03/fun-food-logo-1080x1080.jpg" alt="logo" class="bd-placeholder-img" width="250" height="250" />
        </div>
      </div>
    </div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form-control my-2" %>
  </div>

  <div class="form-field my-3">
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit, class:"form-control my-2" %>
  </div>

  <div class="form-field">
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, class:"form-control my-2" %>
  </div>

  <div class="form-field my-3">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class:"form-control my-2" %>
  </div>

  <div class="form-field">
    <% form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, value:current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<% content_for :title, "#{@food.name}" %>

<div class="row justify-content-center my-5">
  <div class="col-6 card p-5">
    <h1 class="text-center">Editing food</h1>

    <%= render "form", food: @food %>

    <br>

    <div>
      <%= link_to "Show this food", @food %> |
      <%= link_to "Back to foods", foods_path %>
    </div>
  </div>
</div>

app/views/foods/index.html.erb
<% content_for :title, "Food" %>

<h1>Foods</h1>

<% if user_signed_in? %>
<%= link_to "New food", new_food_path, class:"btn btn-outline-secondary mt-3" %>
<% end %>



<!--<div class="row my-5">
  <% @foods.each do |food| %>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0"><%= food.name %></h3>
          <div class="mb-1 text-body-secondary"><%= food.created_at.strftime('%d %b %y') %></div>
          <p class="card-text mb-ato">Price: $<%= food.price %></p>
          <i class="d-inline-block mb-2 text-primary-emphasis">Created by: <%= food.user.name %></i>
          <%= link_to "Show this food", food, class:"icon-link gap-1 icon-link-hover stretched-link" %>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="https://scalebranding.com/wp-content/uploads/2020/03/fun-food-logo-1080x1080.jpg" alt="logo" class="bd-placeholder-img" width="250" height="250" />
        </div>
      </div>
    </div>
  <% end %>
</div> -->

<table class="table table-bordered my-5">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurment unit</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <td><%= food.name%></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td>
        <% if can?(:delete, food) %>
          <%= button_to "Delete this food", food, method: :delete, class:"btn btn-danger my-3" %>
        <% end %>
      <td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/foods/new.html.erb
<% content_for :title, "Add new food" %>

<div class="row justify-content-center my-5">
  <div class="col-6 card p-5">
    <h1 class="text-center">New food</h1>

    <%= render "form", food: @food %>

    <br>

    <div>
      <%= link_to "Back to foods", foods_path %>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<% content_for :title, "#{@food.name}" %>

<div class="row my-5">
  <div class="col-md-12">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <h3 class="mb-0"><%= @food.name %></h3>
        <div class="mb-1 text-body-secondary"><%= @food.created_at.strftime('%d %b %y') %></div>
        <p class="card-text mb-ato">Price: $<%= @food.price %></p>
        <i class="d-inline-block mb-2 text-primary-emphasis">Created by: <%= @food.user.name %></i>
        <div class="d-flex gap-5 mt-3">
        <% if can?(:edit, @food) %>
          <%= link_to "Edit this food", edit_food_path(@food) %>
        <% end %>
          <%= link_to "Back to foods", foods_path %>
        </div>
        <% if can?(:delete, @food) %>
          <%= button_to "Delete this food", @food, method: :delete, class:"btn btn-danger my-3" %>
        <% end %>
      </div>
      <div class="col-auto d-none d-lg-block">
        <img src="https://scalebranding.com/wp-content/uploads/2020/03/fun-food-logo-1080x1080.jpg" alt="logo" class="bd-placeholder-img" width="250" height="250" />
      </div>
    </div>
  </div>
</div>