config/routes.rb
Rails.application.routes.draw do
  # get 'shopping_lists/show'
  get 'shopping_list', to: 'shopping_lists#show'
    get 'public_recipes', to: 'recipes#public_recipes'

  resources :recipes do
    member do
      patch :toggle
    end
    resources :recipes_foods, only: [:new, :create]
  end
  resources :foods 
  # devise_for :users
  devise_for :users, sign_out_via: [:get, :delete]

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
  before_action :find_recipe

  def new
    @recipe_food = RecipeFood.new(recipe_id: @recipe.id)
    @foods = Food.all
  end

  def create
    @recipes_food = RecipeFood.new(recipe_food_params)
    @foods = Food.all
    if @recipes_food.save
      redirect_to recipe_path(@recipe), notice: 'Ingridient was successfully created.'
    else
      render :new
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :quantity, :food_id)
  end

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/views/recipes_foods/new.html.erb
<%= form_with(model: @recipe_food, url: recipe_recipes_foods_path(@recipe)) do |form| %>

  <%= form.hidden_field :recipe_id, value: @recipe.id %>

  <div class="form-field my-3">
  <%= form.label :food_id, style: "display: block" %>
    <%= form.collection_select :food_id, @foods, :id, :name, prompt: "Select a food", class: "form-control my-2 mb-2" %>
  </div>

   <div class="form-field my-3">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class:"form-control my-2" %>
  </div>

  <div>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>