config/routes.rb
Rails.application.routes.draw do
  # get 'shopping_lists/show'
  get 'shopping_list', to: 'shopping_lists#show'
    get 'public_recipes', to: 'recipes#public_recipes'

  resources :recipes do
    member do
      patch :toggle
    end
    resources :recipes_foods, only: [:new, :create]
  end
  resources :foods 
  # devise_for :users
  devise_for :users, sign_out_via: [:get, :delete]

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to 'Recipe app', root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Foods', foods_path, class:"nav-link" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Recipes', recipes_path, class:"nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Public Recipes', public_recipes_path, class:"nav-link" %>
            </li>
          </ul>
          <div>
            <ul class="navbar-nav mr-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>

app/views/layouts/_notice.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blogapp - <%= yield(:title) || "Default Title" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
    integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
    crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <%# Navbar %>
    <%= render 'layouts/navbar' %>
    
    <main class="container my-5">
      <%if notice %>
        <%= render 'layouts/notice' %>
      <%end%>
      <%if alert %>
        <%= render 'layouts/alert' %>
      <%end%>
      <%= yield %>
    </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>